name: Docker Image CI
on: 
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - shell: bash
    - uses: actions/checkout@v2
    - name: docker login 
      env:
        SDOCKERUSER: ${{secrets.DOCKER_USERNAME}}
        SDOCKERPASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: 
        docker login -u "$SDOCKERUSER" -p "$SDOCKERPASSWORD"
    - name: Build the Docker image 
      run: docker build . --progress plain --tag hazemjaki/chipyard:S{{ github.sha }}
    
    - name: Docker Push
      run: docker push hazemjaki/chipyard:S{{ github.sha }}
