name: Docker Image CI
on: 
  push:
    branches:
      - ChipyardOnDevice
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    
    - name: docker login 
      env:
        SDOCKERUSER: ${{secrets.DOCKER_USERNAME}}
        SDOCKERPASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: 
        docker login -u $SDOCKERUSER -p $SDOCKERPASSWORD
    - name: Build the Docker image 
      run: docker build --progress plain -t hazemjaki/chipyard:ChipyardOnDevice .
    
    - name: Docker Push
      run: docker push hazemjaki/chipyard:ChipyardOnDevice
